apiVersion: v1
kind: Service
metadata:
  name: sparkjavaaks
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: sparkjavaaks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkjavaaks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sparkjavaaks
  template:
    metadata:
      labels:
        app: sparkjavaaks
    spec:
      containers:
      - name: sparkjavaaks
        image: voxxedacr.azurecr.io/sparkhello:latest
        ports:
        - containerPort: 8080
